using System;
using System.IO;
using System.Text;

namespace GetDataSet.Builder
{
    class Program
    {


        static void Main(string[] args)
        {
            GenerateRepoFilesEnum();
        }
        static void GenerateRepoFilesEnum()
        {
            string RepoFilesPath = @"F:\Source\GetDataSet\GetDataSet.Test\TestRepo\RepoFiles.cs";
            string InitialDeclaration = "//AUTO-GENERATED by GetDataSet.Builder\nusing System.ComponentModel;\npublic enum RepoFiles\n{\n";
            File.Delete(RepoFilesPath);
            File.WriteAllText(RepoFilesPath, InitialDeclaration);
            StringBuilder Builder = new StringBuilder();
            using (StreamWriter EnumStream = File.AppendText(@"F:\Source\GetDataSet\GetDataSet.Test\TestRepo\RepoFiles.cs"))
            {
                foreach (var f in Directory.GetFiles(@"F:\Source\GetDataSet\GetDataSet.Test\TestRepo\HTML"))
                {
                    Builder.Append(GetRepoFilesEnumValue(f));
                }
                string ResultString = RemoveLastNChars(Builder, 3) + "\n}";
                EnumStream.Write(ResultString);
            }
        }
        static string RemoveLastNChars(StringBuilder Builder, int N)
        {
            return Builder.ToString(0, Builder.Length - N);
        }
        static string GetRepoFilesEnumValue(string file)
        {
            int NameStart = file.LastIndexOf('\\') + 1;
            int ExtensionDot = file.LastIndexOf('.');
            string EnumValue = @$"    [Description(@""{file}"")]
                {file.Substring(NameStart, ExtensionDot - NameStart)},
            ";
            return EnumValue;
        }
    }
}
