//AUTO-GENERATED by GetDataSet.Builder
using System.ComponentModel;
public enum RepoFiles
{
    [Description(@"F:\Source\GetDataSet\GetDataSet.Test\TestRepo\HTML\InvalidHTML.html")]
                InvalidHTML,
                [Description(@"F:\Source\GetDataSet\GetDataSet.Test\TestRepo\HTML\MendeleyMusicalInstrumentsSearch.html")]
                MendeleyMusicalInstrumentsSearch,
                [Description(@"F:\Source\GetDataSet\GetDataSet.Test\TestRepo\HTML\MendeleyMusicSearch.html")]
                MendeleyMusicSearch,
                [Description(@"F:\Source\GetDataSet\GetDataSet.Test\TestRepo\HTML\MendeleyMusicSearchStripped.html")]
                MendeleyMusicSearchStripped,
                [Description(@"F:\Source\GetDataSet\GetDataSet.Test\TestRepo\HTML\SimpleHTML.html")]
                SimpleHTML,
         
}